/products:
  get:
    summary: Get all products
    responses:
      "200":
        description: List of products
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/schemas/Product"
  post:
    summary: Create a new product
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/schemas/Product"
    responses:
      "201":
        description: Product created
        content:
          application/json:
            schema:
              $ref: "#/schemas/Product"

/products/{id}:
  get:
    summary: Get product by ID
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    responses:
      "200":
        description: Product details
        content:
          application/json:
            schema:
              $ref: "#/schemas/Product"
