openapi: 3.0.0
info:
  title: Fake store API
  description: API for test fake store
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /products:
    get:
      $ref: "./endpoints/products.yaml#/getAllProducts"

    post:
      $ref: "./endpoints/products.yaml#/createProduct"

  /products/{productId}:
    delete:
      $ref: "./endpoints/products.yaml#/deleteProduct"

  /auth/login:
    post:
      $ref: "./endpoints/auth.yaml#/login"

  /auth/register:
    post:
      $ref: "./endpoints/auth.yaml#/register"

  /auth/refresh:
    post:
      $ref: "./endpoints/auth.yaml#/refresh"
